pre-commit:
  commands:
    clean-jupyter:
      priority: 2
      files: git ls-files
      glob: '*.ipynb'
      run: uv run jupyter nbconvert --clear-output --inplace {staged_files}
      stage_fixed: true
    format:
      priority: 2
      files: git ls-files
      glob: '*.{py, ipynb}'
      run: uv run ruff format {staged_files}
      stage_fixed: true
    ruff:
      priority: 2
      files: git ls-files
      glob: '*.py'
      run: uv run ruff check {staged_files} --fix
    test:
      priority: 2
      files: git ls-files
      glob: '*.{py, ipynb}'
      run: uv run pytest
    typecheck:
      priority: 2
      files: git ls-files
      glob: '*.py'
      run: uv run ty check {staged_files}