DATETIME = "Datetime"
TIMESTAMP = "Timestamp"

OPEN = "Open"
HIGH = "High"
LOW = "Low"
CLOSE = "Close"
VOLUME = "Volume"

BBANDS = "Bollinger Bands"
BBANDS_LOWER = "Bollinger Bands: Lower"
BBANDS_MIDDLE = "Bollinger Bands: Middle"
BBANDS_UPPER = "Bollinger Bands: Upper"
EMA_FAST = "Exponential Moving Average: Fast"
EMA_SLOW = "Exponential Moving Average: Slow"
MACD = "Moving Average Convergence Divergence"
MACD_SIGNAL = "Moving Average Convergence Divergence: Signal"
MACD_HISTOGRAM = "Moving Average Convergence Divergence: Histogram"
RSI = "Relative Strength Index"

ACTION = "Action"
INDEX = "Index"
PROCEEDS = "Proceeds"
PROFIT_LOSS = "Profit/Loss"
SHARES = "Shares"
TOTAL_RETURN = "Total Return"
TRADE_PRICE = "Trade Price"
TRADE_SIGNAL = "Trade Signal"
