DATETIME = "Datetime"
TIMESTAMP = "Timestamp"

OPEN = "Open"
HIGH = "High"
LOW = "Low"
CLOSE = "Close"
VOLUME = "Volume"

BBANDS = "Bollinger Bands"
BBANDS_LOWER = "Bollinger Bands: Lower"
BBANDS_MIDDLE = "Bollinger Bands: Middle"
BBANDS_UPPER = "Bollinger Bands: Upper"
BBANDS_LOWER_BOUNCE = "Bollinger Bands: Lower Bounce"
BBANDS_UPPER_BOUNCE = "Bollinger Bands: Upper Bounce"

EMA_FAST = "Exponential Moving Average: Fast"
EMA_SLOW = "Exponential Moving Average: Slow"
EMA_GOLDEN_CROSS = "Exponential Moving Average: Golden Cross"
EMA_DEATH_CROSS = "Exponential Moving Average: Death Cross"

MACD = "Moving Average Convergence Divergence"
MACD_SIGNAL = "Moving Average Convergence Divergence: Signal"
MACD_HISTOGRAM = "Moving Average Convergence Divergence: Histogram"
MACD_BULLISH_CROSS = "Moving Average Convergence Divergence: Bullish Cross"
MACD_BEARISH_CROSS = "Moving Average Convergence Divergence: Bearish Cross"

RSI = "Relative Strength Index"
RSI_OVERSOLD = "Relative Strength Index: Oversold"
RSI_OVERBOUGHT = "Relative Strength Index: Overbought"

ACTION = "Action"
INDEX = "Index"
PROCEEDS = "Proceeds"
PROFIT_LOSS = "Profit/Loss"
SHARES = "Shares"
TOTAL_RETURN = "Total Return"
TRADE_PRICE = "Trade Price"
TRADE_SIGNAL = "Trade Signal"
