TIMESTAMP = "Timestamp"
DATETIME = "Datetime"

OPEN = "Open"
HIGH = "High"
LOW = "Low"
CLOSE = "Close"
VOLUME = "Volume"

BBANDS_LOWER = "Bollinger Bands: Lower"
BBANDS_MIDDLE = "Bollinger Bands: Middle"
BBANDS_UPPER = "Bollinger Bands: Upper"
EMA_6 = "Exponential Moving Average: 6 period"
EMA_9 = "Exponential Moving Average: 9 periods"
EMA_12 = "Exponential Moving Average: 12 periods"
MACD = "Moving Average Convergence Divergence"
MACD_SIGNAL = "Moving Average Convergence Divergence: Signal"
MACD_HISTOGRAM = "Moving Average Convergence Divergence: Histogram"
RSI = "Relative Strength Index"
