# Colors
BLACK = "#000000"
HONOLULU_BLUE = "#1F77B4"
IMPERIAL_RED_LIGHT = "#F48A88"
IMPERIAL_RED_MAIN = "#F0534F"
PERSIAN_GREEN_LIGHT = "#6BC2BA"
PERSIAN_GREEN_MAIN = "#27A69A"
YELLOW_SEA = "#FFA80E"

# Labels
BBANDS = "Bollinger Bands"
BBANDS_LOWER = "Bollinger Bands: Lower"
BBANDS_MIDDLE = "Bollinger Bands: Middle"
BBANDS_UPPER = "Bollinger Bands: Upper"
CLOSE = "Close"
DATETIME = "Datetime"
EMA_FAST = "Exponential Moving Average: Fast"
EMA_SLOW = "Exponential Moving Average: Slow"
EUR = "EUR"
HIGH = "High"
LOW = "Low"
MACD = "Moving Average Convergence Divergence"
MACD_HISTOGRAM = "Moving Average Convergence Divergence: Histogram"
MACD_SIGNAL = "Moving Average Convergence Divergence: Signal"
MAGNITUDE = "Magnitude"
OPEN = "Open"
RSI = "Relative Strength Index"
TIMESTAMP = "Timestamp"
VOLUME = "Volume"
