from typing import Any

class BaseError(Exception): ...
class ExchangeError(BaseError): ...
class NetworkError(BaseError): ...

class Exchange:
    id: str
    timeframes: dict[str, str]
    def __init__(self, config: dict[str, Any] = ...) -> None: ...
    def load_markets(
        self, reload: bool = ..., params: dict[str, Any] = ...
    ) -> dict[str, Any]: ...
    def fetch_ohlcv(
        self,
        symbol: str,
        timeframe: str = ...,
        since: int | None = ...,
        limit: int | None = ...,
        params: dict[str, Any] = ...,
    ) -> list[list[float]]: ...
    @staticmethod
    def parse_timeframe(timeframe: str) -> int: ...

exchanges: list[str]

def __getattr__(name: str) -> type[Exchange]: ...
