from datetime import datetime
from typing import Any, Callable, Mapping

class Bitvavo:
    def __init__(self, options: Mapping[str, Any] | None = ...) -> None: ...
    def markets(
        self, options: Mapping[str, Any] | None = ...
    ) -> list[dict[str, Any]]: ...
    def candles(
        self,
        symbol: str,
        interval: str,
        options: Mapping[str, Any] | None = ...,
        limit: int | None = ...,
        start: int | datetime | None = ...,
        end: int | datetime | None = ...,
    ) -> list[Any]: ...
    def tickerPrice(
        self, options: Mapping[str, Any] | None = ...
    ) -> dict[str, Any]: ...
    def trades(
        self, market: str, options: Mapping[str, Any] | None = ...
    ) -> list[dict[str, Any]]: ...
    def balance(
        self, options: Mapping[str, Any] | None = ...
    ) -> list[dict[str, Any]]: ...
    def getRemainingLimit(self) -> int: ...
    def newWebsocket(self) -> BitvavoWebsocket: ...

class BitvavoWebsocket:
    def subscriptionCandles(
        self, market: str, interval: str, callback: Callable[[dict[str, Any]], None]
    ) -> None: ...
    def setErrorCallback(self, callback: Callable[[Any], None]) -> None: ...
    def closeSocket(self) -> None: ...
